/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package untisthmscraper.UI;


import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URISyntaxException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import untisthmscraper.PlanChooseParser;
import untisthmscraper.ResultOpener;
import untisthmscraper.UntisTable;

/**
 *
 * @author fabian
 */
public class UI extends javax.swing.JFrame {
    
    public PlanChooseParser parser;

    /**
     * Creates new form NewJFrame
     * @throws java.io.IOException
     */
    public UI() throws IOException {
        this.parser = new PlanChooseParser();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListOShorts = new javax.swing.JList();
        Label1Shorts = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListOPlans = new javax.swing.JList();
        HTMLgenButton = new javax.swing.JButton();
        Label1Plans = new javax.swing.JLabel();
        usedLibs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListOShorts.setModel(new javax.swing.AbstractListModel() {
            String[] strings = parser.getKuerzel();
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListOShorts.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListOShortsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListOShorts);

        Label1Shorts.setText("Bereiche");

        ListOPlans.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Wähle einen Fachbereich aus", "dann werden hier Pläne angezeigt" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListOPlans);

        HTMLgenButton.setText("Generate HTML");
        HTMLgenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HTMLgenButtonActionPerformed(evt);
            }
        });

        Label1Plans.setText("Pläne");

        usedLibs.setText("Bibliotheken: jSoup, Bootstrap");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label1Plans, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label1Shorts)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(usedLibs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HTMLgenButton))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label1Shorts)
                    .addComponent(Label1Plans))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HTMLgenButton)
                    .addComponent(usedLibs))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HTMLgenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HTMLgenButtonActionPerformed
        
        try {
            List     selectedValuesList = ListOPlans.getSelectedValuesList();
            Iterator iterator           = selectedValuesList.iterator();
            int      i                  = 0;
            String[] keys;
                     keys               = new String[selectedValuesList.size()];
            
            while(iterator.hasNext()) {
                keys[i] = (String) iterator.next();
                i++;
            }
            
            
            String[] links;
                     links = parser.getLinks(keys);
            UntisTable table = new UntisTable(links);
            UntisTable.createOutputFile(table.HTMLGen());
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ResultOpener.open();
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_HTMLgenButtonActionPerformed

    private void ListOShortsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListOShortsValueChanged
        // TODO add your handling code here:
        String b = (String)ListOShorts.getSelectedValue();
        String s[] = parser.getPlaene(b);
       
        ListOPlans.setListData(s);
        
    }//GEN-LAST:event_ListOShortsValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac OS X".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new UI().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HTMLgenButton;
    private javax.swing.JLabel Label1Plans;
    private javax.swing.JLabel Label1Shorts;
    private javax.swing.JList ListOPlans;
    private javax.swing.JList ListOShorts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel usedLibs;
    // End of variables declaration//GEN-END:variables
}
